### PR TITLE
New icon library integrated into css

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
This is a PR to adjust the CSS to handle the new icon library.

Visible changes to normal width default and CRC styles are minimal. Default mobile width gets access to more buttons (calc and index) by just displaying icons.

Samples are available here:
https://computerscience.chemeketa.edu/ascholer/pretext-test/icons/html/default/sample-book.html
https://computerscience.chemeketa.edu/ascholer/pretext-test/icons/html/crc/sample-book.html

Marked as draft while under discussion.

Will need to be sync'd to pretext PR: https://github.com/PreTeXtBook/pretext/pull/2049

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
This should be complete.

Will need to be sync'd to pretext PR: https://github.com/PreTeXtBook/pretext/pull/2049

**Comment by rbeezer** [comment]
This is a build of the **sample book** as if it were to be hosted on Runestone, with https://github.com/PreTeXtBook/pretext/pull/2049 applied, so that all the navbar elements are present, etc.  If you need a sample article build, just holler - easy enough to put up.

https://pretextbook.org/beta/navbar-2023-09-01

When CSS is clear, I'll get back to the HTML pull request (which looks fine right now).

**Comment by rbeezer** [comment]
Oops, I didn't see this was merged!  But I'm not sure the CSS is in effect?  Is there some adjustment based on the 0.7/main swap?

**Comment by ascholerChemeketa** [comment]
I believe David said he deployed it as version 0.8/

The 0.8 does appear to be delivering these versions of the CSS. Example:
https://pretextbook.org/css/0.8/navbar_default.css

Andrew Scholer (he/him/his)
Computer Science Instructor/Program Chair
Chemeketa Community College
503.589.7649
computerscience.chemeketa.edu/people/andrew-scholer/

**Pull request merged**
