### PR TITLE
Native search improvement

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Moves search input into the results panel and searches on type
Adds results snippets & highlighting
Stores search query between searches

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
These three PR's must be sync'd:
https://github.com/PreTeXtBook/pretext/pull/2057
https://github.com/PreTeXtBook/CSS_core/pull/69
https://github.com/PreTeXtBook/JS_core/pull/56

**Comment by ascholerChemeketa** [comment]
Live demos for default and reference style searches:
https://computerscience.chemeketa.edu/ascholer/pretext-test/search/html/default/sets-sage.html
https://computerscience.chemeketa.edu/ascholer/pretext-test/search/html/reference/sets-sage.html

**Comment by rbeezer** [comment]
See #2057 for test HTML to work with.

**Comment by rbeezer** [comment]
Oops, that's https://github.com/PreTeXtBook/pretext/pull/2057

**Pull request merged**
